"""update_dossier_model_with_defaults

Revision ID: b8e464305a5c
Revises: d45d622954bc
Create Date: 2025-02-18 01:25:20.929517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8e464305a5c'
down_revision: Union[str, None] = 'd45d622954bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dossiers', sa.Column('type', sa.String(), server_default='achat', nullable=False))
    op.add_column('dossiers', sa.Column('monthly_income', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('dossiers', sa.Column('employment_contract_type', sa.String(), server_default='cdi', nullable=False))
    op.add_column('dossiers', sa.Column('employer_name', sa.String(), server_default='', nullable=False))
    op.add_column('dossiers', sa.Column('employment_start_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('dossiers', sa.Column('current_loans_monthly_payments', sa.Float(), nullable=True))
    op.add_column('dossiers', sa.Column('comments', sa.String(), nullable=True))
    op.add_column('dossiers', sa.Column('admin_comments', sa.String(), nullable=True))
    op.add_column('dossiers', sa.Column('desired_loan_duration', sa.Integer(), nullable=True))
    op.alter_column('dossiers', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='dossierstatus'),
               type_=sa.String(),
               existing_nullable=True,
               server_default='en_attente')
    op.alter_column('dossiers', 'documents',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using="documents::jsonb",
               server_default='{}')
    op.drop_column('dossiers', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dossiers', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('dossiers', 'documents',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using="documents::text")
    op.alter_column('dossiers', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='dossierstatus'),
               existing_nullable=True)
    op.drop_column('dossiers', 'desired_loan_duration')
    op.drop_column('dossiers', 'admin_comments')
    op.drop_column('dossiers', 'comments')
    op.drop_column('dossiers', 'current_loans_monthly_payments')
    op.drop_column('dossiers', 'employment_start_date')
    op.drop_column('dossiers', 'employer_name')
    op.drop_column('dossiers', 'employment_contract_type')
    op.drop_column('dossiers', 'monthly_income')
    op.drop_column('dossiers', 'type')
    # ### end Alembic commands ###
