"""add_rental_services_table

Revision ID: 3d336155629c
Revises: 5ed235b06bdc
Create Date: 2025-02-18 02:44:55.096556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d336155629c'
down_revision: Union[str, None] = '5ed235b06bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ASSURANCE', 'ASSISTANCE', 'ENTRETIEN', 'CONTROLE_TECHNIQUE', name='servicetype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_per_month', sa.Float(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('terms_and_conditions', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIF', 'INACTIF', 'EN_ATTENTE', 'EXPIRE', name='servicestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_services_id'), 'rental_services', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_services_id'), table_name='rental_services')
    op.drop_table('rental_services')
    # ### end Alembic commands ###
